/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FromUri = string | null;
export type Name = string | null;
export type Title = string | null;
export type Datasets = Dataset[] | null;
export type FromUri1 = string | null;
export type Name1 = string;
export type Prefix = string | null;
export type Title1 = string | null;
export type License = string | null;
export type Summary = string | null;
export type Description = string | null;
export type Url = string | null;
export type UpdatedAt = string | null;
export type Version = string | null;
export type Category =
  | (
      | "news"
      | "leak"
      | "land"
      | "gazette"
      | "court"
      | "company"
      | "sanctions"
      | "procurement"
      | "finance"
      | "grey"
      | "library"
      | "license"
      | "regulatory"
      | "poi"
      | "customs"
      | "census"
      | "transport"
      | "casefile"
      | "other"
    )
  | null;
export type FromUri2 = string | null;
export type Name2 = string;
export type Url1 = string;
export type Description1 = string | null;
export type Country = string | null;
export type CountryLabel = string | null;
export type Official = boolean;
export type LogoUrl = string | null;
export type FromUri3 = string | null;
export type Start = string | string | null;
export type End = string | string | null;
export type Frequency = ("unknown" | "never" | "hourly" | "daily" | "weekly" | "monthly" | "annually") | null;
export type Countries = string[] | null;
export type Schedule = string | null;
export type FromUri4 = string | null;
export type Total = number;
export type Countries1 = Country1[] | null;
export type FromUri5 = string | null;
export type Code = string;
export type Count = number;
export type Label = string | null;
export type Schemata1 = Schema[] | null;
export type FromUri6 = string | null;
export type Name3 = string;
export type Count1 = number;
export type Label1 = string;
export type Plural = string;
export type EntityCount = number | null;
export type Resources = Resource[] | null;
export type FromUri7 = string | null;
export type Name4 = string;
export type Url2 = string;
export type Title2 = string | null;
export type Checksum = string | null;
export type Timestamp = string | null;
export type MimeType = string | null;
export type MimeTypeLabel = string | null;
export type Size = number | null;
export type IndexUrl = string | null;
export type Catalog1 = string | null;
export type Countries2 = string[] | null;
export type InfoUrl = string | null;
export type DataUrl = string | null;
export type GitRepo = string | null;
export type Uri = string | null;
export type FromUri8 = string | null;
export type Name5 = string;
export type Description2 = string | null;
export type Url3 = string | null;
export type LogoUrl1 = string | null;
export type UpdatedAt1 = string | null;
export type Description3 = string | null;
export type Url4 = string | null;
export type Uri1 = string | null;
export type LogoUrl2 = string | null;
export type GitRepo1 = string | null;

export interface Catalog {
  from_uri?: FromUri;
  name?: Name;
  title?: Title;
  datasets?: Datasets;
  updated_at?: UpdatedAt1;
  description?: Description3;
  maintainer?: Maintainer | null;
  publisher?: Publisher | null;
  url?: Url4;
  uri?: Uri1;
  logo_url?: LogoUrl2;
  git_repo?: GitRepo1;
  [k: string]: unknown;
}
export interface Dataset {
  from_uri?: FromUri1;
  name: Name1;
  prefix?: Prefix;
  title?: Title1;
  license?: License;
  summary?: Summary;
  description?: Description;
  url?: Url;
  updated_at?: UpdatedAt;
  version?: Version;
  category?: Category;
  publisher?: Publisher | null;
  coverage?: Coverage | null;
  things?: Schemata | null;
  intervals?: Schemata | null;
  entity_count?: EntityCount;
  resources?: Resources;
  index_url?: IndexUrl;
  catalog?: Catalog1;
  countries?: Countries2;
  info_url?: InfoUrl;
  data_url?: DataUrl;
  git_repo?: GitRepo;
  uri?: Uri;
  maintainer?: Maintainer | null;
  [k: string]: unknown;
}
export interface Publisher {
  from_uri?: FromUri2;
  name: Name2;
  url: Url1;
  description?: Description1;
  country?: Country;
  country_label?: CountryLabel;
  official?: Official;
  logo_url?: LogoUrl;
  [k: string]: unknown;
}
export interface Coverage {
  from_uri?: FromUri3;
  start?: Start;
  end?: End;
  frequency?: Frequency;
  countries?: Countries;
  schedule?: Schedule;
  [k: string]: unknown;
}
export interface Schemata {
  from_uri?: FromUri4;
  total?: Total;
  countries?: Countries1;
  schemata?: Schemata1;
  [k: string]: unknown;
}
export interface Country1 {
  from_uri?: FromUri5;
  code: Code;
  count: Count;
  label?: Label;
  [k: string]: unknown;
}
export interface Schema {
  from_uri?: FromUri6;
  name: Name3;
  count: Count1;
  label: Label1;
  plural: Plural;
  [k: string]: unknown;
}
export interface Resource {
  from_uri?: FromUri7;
  name: Name4;
  url: Url2;
  title?: Title2;
  checksum?: Checksum;
  timestamp?: Timestamp;
  mime_type?: MimeType;
  mime_type_label?: MimeTypeLabel;
  size?: Size;
  [k: string]: unknown;
}
/**
 * this is our own addition
 */
export interface Maintainer {
  from_uri?: FromUri8;
  name: Name5;
  description?: Description2;
  url?: Url3;
  logo_url?: LogoUrl1;
  [k: string]: unknown;
}
