/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FromUri = string | null;
export type FromUri1 = string | null;
export type Start = string | null;
export type End = string | null;
export type Frequency = ("unknown" | "never" | "hourly" | "daily" | "weekly" | "monthly" | "annually") | null;
export type Countries = string[] | null;
export type Schedule = string | null;
export type FromUri2 = string | null;
export type Total = number;
export type Countries1 = Country[] | null;
export type FromUri3 = string | null;
export type Code = string;
export type Count = number;
export type Label = string | null;
export type Schemata1 = Schema[] | null;
export type FromUri4 = string | null;
export type Name = string;
export type Count1 = number;
export type Label1 = string;
export type Plural = string;
export type EntityCount = number | null;

export interface DatasetStats {
  from_uri?: FromUri;
  coverage: Coverage;
  things: Schemata;
  intervals: Schemata;
  entity_count?: EntityCount;
  [k: string]: unknown;
}
export interface Coverage {
  from_uri?: FromUri1;
  start?: Start;
  end?: End;
  frequency?: Frequency;
  countries?: Countries;
  schedule?: Schedule;
  [k: string]: unknown;
}
export interface Schemata {
  from_uri?: FromUri2;
  total?: Total;
  countries?: Countries1;
  schemata?: Schemata1;
  [k: string]: unknown;
}
export interface Country {
  from_uri?: FromUri3;
  code: Code;
  count: Count;
  label?: Label;
  [k: string]: unknown;
}
export interface Schema {
  from_uri?: FromUri4;
  name: Name;
  count: Count1;
  label: Label1;
  plural: Plural;
  [k: string]: unknown;
}
