/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Entity = Entity1;
export type Id = string;
export type Caption = string;
export type Schema = string;
export type Datasets = string[];
export type Referents = string[];

export interface Entity1 {
  id: Id;
  caption: Caption;
  schema: Schema;
  properties: Properties;
  datasets?: Datasets;
  referents?: Referents;
  [k: string]: unknown;
}
export interface Properties {
  [k: string]: (string | Entity1)[];
}
