/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FromUri = string | null;
export type Name = string;
export type Description = string | null;
export type Url = string | null;
export type LogoUrl = string | null;

/**
 * this is our own addition
 */
export interface Maintainer {
  from_uri?: FromUri;
  name: Name;
  description?: Description;
  url?: Url;
  logo_url?: LogoUrl;
  [k: string]: unknown;
}
