/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FromUri = string | null;
export type Name = string;
export type Url = string;
export type Description = string | null;
export type Country = string | null;
export type CountryLabel = string | null;
export type Official = boolean;
export type LogoUrl = string | null;

export interface Publisher {
  from_uri?: FromUri;
  name: Name;
  url: Url;
  description?: Description;
  country?: Country;
  country_label?: CountryLabel;
  official?: Official;
  logo_url?: LogoUrl;
  [k: string]: unknown;
}
