/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FromUri = string | null;
export type Name = string;
export type Url = string;
export type Title = string | null;
export type Checksum = string | null;
export type Timestamp = string | null;
export type MimeType = string | null;
export type MimeTypeLabel = string | null;
export type Size = number | null;

export interface Resource {
  from_uri?: FromUri;
  name: Name;
  url: Url;
  title?: Title;
  checksum?: Checksum;
  timestamp?: Timestamp;
  mime_type?: MimeType;
  mime_type_label?: MimeTypeLabel;
  size?: Size;
  [k: string]: unknown;
}
